### ISSUE TITLE
Misc checklist for 2.3.0

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#142]
yea

- [ ] Add custom dialog boxes for Fluent theme
- [x] Make Job ID copyable when clicking on the server stats notification
- [x] Make time started playing on rich presence persist through teleports within the same universe
- [x] Look into forking wpf-ui to fix the numerous issues it has ([pizzaboxer/wpfui](https://github.com/pizzaboxer/wpfui))
   - [x] Crashing when dwmapi.dll can't be found (how the fuck) 
      - #170
      - #173
   - [ ] Title bar colour showing when it shouldn't on Windows 11
      - #92
   - [ ] Progress bar marquee having non-rounded corners
      - #96 
      - #114
- [x] ~Add FastFlag editor~ 
   - scrapped for now, too difficult and inefficient under current circumstances, added button to open fastflags file though. at some point i want to make it look like [windows terminal's settings listing](https://user-images.githubusercontent.com/41478239/235649227-a2612666-4036-4809-aaa8-73debc7dbb30.png)
- [x] Check for free disk space based on package manifest sizes
- [x] Fix Direct3D 11 incorrectly being enforced
- [ ] Fetch selectable channel list from [RDHT](https://github.com/bluepilledgreat/Roblox-DeployHistory-Tracker)
- [x] Rework DeployManager (less OOP, more functional)
- [x] Refined logo?
- [x] Automatic cleanup of old log files
- [x] Add more options for automatic channel change behaviour (always change, always prompt, never change)
   - #166
- [ ] Mod preset for changing emoji fonts
   - #148
- [x] ~Support for Roblox Client Optimizer flags~ 
   - scrapped because lmao
   -  #121
- ReShade improvements (yes its on its way out but who cares)
   - lol nvm
   - [x] ~Fix bug when synchronizing ReShade config between version/mods folder~
   - [x] ~Add clearer statuses instead of just "Configuring/Downloading ReShade..."~

**Comment by zachariapopcorn** [comment]
Can you have it an option where the job id is copied to the clipboard on game start?

**Comment by pizzaboxer** [comment]
I'd rather not do that, I can see that becoming very confusing and annoying very quickly.
