### ISSUE TITLE
Misc checklist for 2.4.0

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#183]
feat. the stuff that didn't make it into 2.3.0 :(
don't expect much of this to materialize soon though, i'm tied up in school work rn

- [x] Add custom dialog boxes for Fluent theme
- [x] Add proper FastFlag editor (? - [windows terminal's settings listing](https://user-images.githubusercontent.com/41478239/235649227-a2612666-4036-4809-aaa8-73debc7dbb30.png)) OR add better handling for invalid JSON edits
- [x] Mod preset for changing emoji fonts - #148
- [x] Make hints on how to open the menu and how to uninstall Bloxstrap more obvious
- [x] Add option to use pre-2013 mouse cursor
- [x] Add support for games to signal data and messages to Bloxstrap - #171
- [x] Add FastFlag preset for old materials - #215
- [x] Add FastFlag preset for allowing GUI hiding - https://github.com/pizzaboxer/bloxstrap/issues/230#issuecomment-1542966228
- [x] Add mod preset for emulating old character sounds
- [x] Add fake Hyperion bootstrapper as a style
- [x] Auto apply Vulkan minimize fix flag if Vulkan is enabled
- [x] Better Wiki help topics for options that require more detail (what they do, usage, etc, instead of just a short description)
- [x] Move automatic channel change option from Behaviour to Installation tab (it's in the right place but it's just not intuitive) 
- [x] Overhaul exception dialog management (unified style, better handling, more friendly, etc) - #214
- [x] Improve error handling for HTTP requests (more global verbosity w/ middleware, etc)
- [x] Improve handling of Roblox updates when there's a Roblox instance running - #253
- [x] Set approximate program size (can be computed from rbxpkgmanifest, both packed and raw sizes)
- [x] Improve handling for when Bloxstrap is launched twice (only cancel launch if same game is being launched) - #212
- [x] Add support for the new 2023/v4 menu
- [x] Prevent multiple instances of the menu from opening
- [x] Explore possibility of disabling desktop app without breaking deeplinking (is Mobile.rbxl loaded from disk every time?)
- [x] Add option to use old avatar editor background (Mobile.rbxl) - #353
- [x] Only allow auto updater to be enabled if building from Actions/defined macro
- [x] Better handling of how the user chooses the install location (more warnings, auto corrections, etc) - #314 
- [x] Add notice for people who installed N versions of Windows (no mfplat.dll - does stock autoinstall it?)
- [x] Roblox debug features :D (flag state, http tracing, proxy config, etc)
- [x] Fully cleanup Bloxstrap folder after install (is this possible? delete after reboot flag, etc)
 - WPF-UI forking ([pizzaboxer/wpfui](https://github.com/pizzaboxer/wpfui))
   - [x] Progress bar marquee having non-rounded corners - #96, #114
   - [x] Move more accurate styling over to there instead of doing it application level
- [x] Add option to easy swap out all fonts
- [x] Default to LIVE if no launch channel set
- [x] When prompting channel change, only suggest changing to enrolled channel once until next enrollment change
- [x] Add popup menu for notification area icon (+ componetize as part of UI?) - #186, #375
- [x] Investigate corruption when extracting packages (#395)
- [x] Investigate logger backlogging not working
- [x] Handle exception for desktop icon creation (#410)
- [x] Mitigate stuck rich presences (#411)
- [x] Add support for Windows 11 Build 21996 (June 2021 leak, because people use it???) - #413
- [x] Better handling of UAC

**Comment by pizzaboxer** [comment]
whoops that was supposed to tag #171

**Comment by user1126s** [comment]
when is 2.4.0 coming out? super excited for the fake hyperion load style!
Also If Roblox Whitelists reshade, roshade and fps unlocker then would you add them back?
Love your work tho!

**Comment by user1126s** [comment]
also just for information, have you signed this petition for roblox to whitelist roshade?
https://www.change.org/p/save-roblox-shaders-support-the-community-s-call-for-roblox-to-whitelist-reshade?redirect=false

**Comment by user1126s** [comment]
this one. its already at 3,500 signs so i think they will whitelist them.

**Comment by user1126s** [comment]
yo pizzaboxer where did my comments go?

**Comment by pizzaboxer** [comment]
> when is 2.4.0 coming out? super excited for the fake hyperion load style! Also If Roblox Whitelists reshade, roshade and fps unlocker then would you add them back? Love your work tho!

If they whitelist ReShade, then yeah I'll add it back. FPS unlocker won't be added back since it was already planned to be replaced outright anyway.

**Comment by user1126s** [comment]
also do fps unlocker and that feature in fast flags for removing fps cap act the same?

**Comment by pizzaboxer** [comment]
> also do fps unlocker and that feature in fast flags for removing fps cap act the same?

Not really, no.

**Comment by user1126s** [comment]
oh ok thanks! again, love your work!

**Comment by user1126s** [comment]
hi

**Comment by user1126s** [comment]
h

**Comment by user1126s** [comment]
i'll try to contact zeal (creator of roshade) and see if its possible, if it is, ill inform you.

**Comment by EasternBloxxer** [comment]
menu for toggling certain materials between new and old ones would be neat lol

**Comment by user1126s** [comment]
For The Wiki, im making it for ya

**Comment by user1126s** [comment]
Please quickly tell what should i name it and also the wiki address @pizzaboxer

**Comment by user1126s** [comment]
for now the url and name is Gonna Be Bloxstrap

**Comment by user1126s** [comment]
here it is: https://bloxstrap.fandom.com/wiki/

**Comment by calcalayy** [comment]
> here it is: https://bloxstrap.fandom.com/wiki/

what the fuck

**Comment by 1011025m** [comment]
> here it is: https://bloxstrap.fandom.com/wiki/

this is the stupidest thing i've seen this week, thanks lol.

when we say "wiki" in a github repository, it means the repository has a wiki within itself. in the case of github, you can find it here:
![image](https://github.com/pizzaboxer/bloxstrap/assets/37438176/21f4985c-6149-44cb-8536-978ad5ccae44)

these wikis typically hold the documentations for the project. you can also find similar documentations on other projects/repositories in the form of a readthedocs website, or sometimes their own website if the project is big enough.

a fandom wiki is more for documenting things of a community (such as a game, or anime). this is absolutely unnecessary for bloxstrap. ~~not to mention how terrible fandom wikis are ive literally worked on them for like 7 years it's terrifying~~

you do sound quite young. while im not trying to discourage your contributions i do advise you to stick to suggestions that benefit the software itself.

**Comment by user1126s** [comment]
ok, yea lol, i totally agree, i just want to contribute to bloxstrap in any way possible

**Comment by user1126s** [comment]
i submitted a wiki closure request

**Comment by user1126s** [comment]
![Screenshot_20230519-073522](https://github.com/pizzaboxer/bloxstrap/assets/114283670/70a55fcc-3308-4696-9fb1-20031150f233)
Ezz

**Comment by user1126s** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/114283670/782426c4-267e-43a4-9e1f-a4b2456c160b)
zeal agreed. once reshade is whitelisted, we can put roshade presets in it

**Comment by user1126s** [comment]
@pizzaboxer

**Comment by Cyber2525** [comment]
We already have options to switch between the different roblox menus, but another version came out in June, could you implement it in the list of available menus?
![e68d7934f93a744134b08e77bfb7b86746e405f4](https://github.com/pizzaboxer/bloxstrap/assets/83342792/721f74f2-81cd-4728-977c-cda7d1e6fa90)

**Comment by 1011025m** [comment]
> We already have options to switch between the different roblox menus, but another version came out in June, could you implement it in the list of available menus in the version 2.4.0?
@Cyber2525 Yes, it has already been added. Check commit [a5c3785ed8d6a35868bc169f07e40e889087fd2e](https://github.com/pizzaboxer/bloxstrap/commit/778a67dcb93c5537da5d78b6287eaca15e920ecf)

**Comment by lokzz** [comment]
goofy ahh comments

anyway
found a group of fflags that lets you see network things(?)

```
"DFFlagDebugVisualizationImprovements": "True"
"DFFlagDebugVisualizeAllPropertyChanges": "True"
"DFFlagDebugVisualizerTrackRotationPredictions": "True"
"DFFlagDebugEnableInterpolationVisualizer": "True"
```

after adding these, press ctrl + f8 ingame to toggle menu (over the chatbox)
![image](https://github.com/pizzaboxer/bloxstrap/assets/50368061/ad69c956-d41d-43cf-ab05-62aa54d84935)
do note that after pressing ctrl f8, scrolling will not work until menu is closed again

**Comment by Axelanse** [comment]
> here it is: https://bloxstrap.fandom.com/wiki/

you know "the wiki" refers to the github section named "wiki"?

**Comment by usman36364** [comment]
These planned features for Bloxstrap, like improved FastFlag presets, custom themes, better error handling, and mod support, aim to provide users with more control, customization, and stability in their Roblox experience. Whether it’s tweaking UI elements, refining update handling, or adding legacy features, [Bloxstrap](https://bloxstraps.me/) continues to evolve as the go-to alternative bootstrapper for Roblox
