### ISSUE TITLE
Add to Winget

### ISSUE THREAD

**Issue by sitiom** [pizzaboxer/bloxstrap#47]
I'm planning to add Bloxstrap to [Winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/), but some issues need to be resolved on the Bloxstrap side:

**Issues to Resolve**
- [x] Command-line arguments so Bloxstrap can be installed and upgraded silently
- [x] A silent uninstall switch to suppress this dialog:
![image](https://user-images.githubusercontent.com/56180050/202886915-28c75835-fd41-4d30-a5c7-34349dd82944.png)
- [x] `DisplayVersion` should be properly set in the `Add or Remove Programs` list
![image](https://user-images.githubusercontent.com/56180050/202914215-5fbf2a0f-efed-49b5-9b78-786f91da1928.png)

**Todo**
- [x] Add Bloxstrap to [winget-pkgs](https://github.com/microsoft/winget-pkgs) (https://github.com/microsoft/winget-pkgs/pull/92827)
- [ ] Add [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) workflow (https://github.com/pizzaboxer/bloxstrap/pull/63)

**Comment by sitiom** [comment]
`DisplayVersion` would also have to be properly set in the `Add or Remove Programs` list:
![image](https://user-images.githubusercontent.com/56180050/202886485-f6921bef-ec54-4cd2-ac51-77c801943710.png)

**Comment by pizzaboxer** [comment]
Sure, I'll add those and also the rich presence problem mentioned in the other issue. I'll mark it as being part of v1.5.4 but I won't release it (for now) as so far its fairly minor.
About Winget -- how is maintaining the latest downloadable version done?

**Comment by sitiom** [comment]
> Sure, I'll add those and also the rich presence problem mentioned in the other issue. I'll mark it as being part of v1.5.4 but I won't release it (for now) as so far its fairly minor. About Winget -- how is maintaining the latest downloadable version done?

Once the manifest is added in the https://github.com/microsoft/winget-pkgs repo, you can use the [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) action in your CI to automatically publish updates every release (Examples: [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser)).

I can help you in adding the workflow once I add Bloxstrap to Winget.

**Comment by pizzaboxer** [comment]
Oh nice, I forgot about having an automatic GitHub release workflow. I'll add the -q arg as the arg for silent install/uninstall. I take it that on initial install, it's just supposed to skip the settings dialog and not launch Roblox?

**Comment by sitiom** [comment]
> I take it that on initial install, it's just supposed to skip the settings dialog and not launch Roblox?

Yep, just install with the defaults

**Comment by pizzaboxer** [comment]
What about error handling? Does it just silently quit with an MSI exit code when it encounters an error?

**Comment by sitiom** [comment]
Yeah, it should basically behave as an installer

**Comment by pizzaboxer** [comment]
Added two new args: -quiet and -nolaunch
-quiet will hide the UI and carry out installation automatically, but will still launch Roblox afterwards
-nolaunch will not launch Roblox once bootstrapper stuff is finished
For your use case, you can use `-quiet -nolaunch` for installing and then `-quiet -uninstall` for uninstalling.

**Comment by sitiom** [comment]
Thanks. I have tested it, and everything seems to work as intended.

**Comment by sitiom** [comment]
@pizzaboxer I tried upgrading from 1.5.4 to 1.6.0 with `-quiet -nolaunch` but it doesn't do an upgrade and does nothing. Can you fix this?

**Comment by pizzaboxer** [comment]
Added the -upgrade arg for better clarity, so `-quiet -nolaunch -upgrade` should work now. I don't want to publish a hotfix release just yet, since there's some other stuff I wanna work on first (mostly DPI scaling). Don't know how long that's gonna take, but hopefully not long.

**Comment by pizzaboxer** [comment]
nvm looks like we're getting a hotfix release anyway lol

**Comment by sitiom** [comment]
Ok here we go: https://github.com/microsoft/winget-pkgs/pull/92827

**Comment by pizzaboxer** [comment]
Oh sweet, thank you!

**Comment by sitiom** [comment]
Now on Winget:
![image](https://user-images.githubusercontent.com/56180050/210685925-ebf2daf6-1c64-4447-bb4a-a44dedc8a977.png)

Now all that's left is the workflow: #63

**Comment by khewweifeng** [comment]
Hi @pizzaboxer , it does not show on https://winget.run/search?query=bloxstrap

**Comment by sitiom** [comment]
> Hi @pizzaboxer , it does not show on [winget.run/search?query=bloxstrap](https://winget.run/search?query=bloxstrap)

winget.run is outdated. Use Winstall instead: https://winstall.app/apps/pizzaboxer.Bloxstrap

**Comment by Extravi** [comment]
@sitiom hi I can message him over discord about it also if you want to add me here: cta#4015

**Comment by sitiom** [comment]
Hi, sorry I don't want to be bugged in my Discord anymore 😅

**Comment by Extravi** [comment]
@sitiom you like disappeared also its been over a year i can develop stuff myself look at my repos or pull request

**Comment by Extravi** [comment]
Anyway, this is not the place to discuss it, and I'm not sure why you left like that.

**Comment by sitiom** [comment]
Yeah, I apologize for ghosting, although I am no longer interested in maintaining the installer. Hopefully we are good 🙂

**Comment by Extravi** [comment]
I have no interest in you maintaining the installer; if I wanted to, I could write a new one in C#, and I have made many changes to it without your assistance. It has not been my primary focus; I have been working on my own meta search engine in Flask (TailsX) and have previously worked on other PHP projects.

**Comment by Extravi** [comment]
I've been researching cloud computing and cyber security for the past few months.

**Comment by Extravi** [comment]
I just wanted to add you on Discord to ask why you were ghosting me. I could have contacted you via email or other means over the last year if I had wanted to. I just thought now would be a good time to ask.

**Comment by Extravi** [comment]
If you add me on Discord, there is no need for me to message you about programming or the installer because I can do that myself. I've also changed a lot since then. I did not appear to be in the best mental health at the time, and I was also younger. I am just curious about the ghosting.
